### ISSUE TITLE
Vault as secret backend

### ISSUE THREAD

**Issue by aweris** [mumoshu/flux-repo#1]
Hey @mumoshu, 

   I was planning to start the same project with Vault as a backend. It'll be helpful if you support the Vault as backend too. Please let me know if you want any contribution to that.

**Comment by mumoshu** [comment]
@aweris Hey! Thanks for the request.

This is implemented in aa93e03 and available since v0.2.0. Would you mind giving it a try?

Also, I've implemented it myself as I thought code was a bit messy. It's much better since v0.2.0, so please feel free to experiment with the code-base and submit any pull request from now on!

**Comment by aweris** [comment]
@mumoshu  Hey! That was fast. Thanks! 

I'll test and send PR if it's necessary.
